# 1. Create an Excel data table

In [10]:
import pandas as pd

excel_file = pd.read_excel("table.xlsx")

In [11]:
#Verifying the data types of the variables in the imported file 
excel_file.dtypes

Gender     object
Weight      int64
Height    float64
dtype: object

In [12]:
#Displaying the data from within Python
excel_file

  Gender  Weight  Height
0      F     150    66.0
1      F     138    66.0
2      M     240     NaN
3      M     178    71.0
4      F     130    64.0
5      M     200    74.0
6      F     140    70.0
7      M     220    77.0

# 2. Large data set

In [13]:
#Reading the data into python
csv_file = pd.read_csv("Donations.csv")
csv_file

,Name,Donation,Lifetime,Gifts,YearsSinceFirst,YearsSinceLast,AvgGift,MajorDonor,Promotions,RecentGifts,...,Technical,Sales,Clerical,Farmers,SelfEmployed,Cars,OwnerOccupied,Age55_59,Age60_64,School
0,Yandel Leach,0.0,81.00,15,6.416667,1.166667,5.400000,No,58,3,...,0.07,0.17,0.22,0.01,0.02,0.16,0.41,0.04,0.05,14.0
1,Jaylah Sims,15.0,15.00,1,1.166667,1.166667,15.000000,No,13,1,...,0.01,0.14,0.16,0.01,0.06,0.08,0.90,0.07,0.11,12.0
2,Roger Bush,0.0,15.00,1,1.750000,1.750000,15.000000,No,16,1,...,0.00,0.05,0.32,0.00,0.00,0.03,0.12,0.06,0.03,12.0
3,Maddox Horn,0.0,25.00,2,3.500000,1.250000,12.500000,No,26,1,...,0.07,0.16,0.19,0.06,0.21,0.52,0.79,0.03,0.02,12.3
4,Darrell Walters,0.0,20.00,1,1.333333,1.333333,20.000000,No,12,1,...,0.03,0.07,0.15,0.02,0.05,0.22,0.78,0.06,0.06,12.0
5,Nick Kent,0.0,68.00,6,7.000000,1.583333,11.333333,No,38,2,...,0.02,0.07,0.04,0.14,0.17,0.26,0.67,0.06,0.05,12.0
6,Isabel Curry,0.0,110.00,11,10.166667,1.416667,10.000000,No,38,2,...,0.03,0.05,0.12,0.15,0.15,0.21,0.82,0.08,0.05,12.0
7,Levi Leon,0.0,174.00,26,10.416667,1.500000,6.692308,No,72,3,...,0.04,0.09,0.12,0.01,0.04,0.12,0.57,0.06,0.06,12.0
8,Zack Bradshaw,0.0,20.00,1,1.750000,1.750000,20.000000,No,15,1,...,0.02,0.16,0.18,0.03,0.03,0.22,0.90,0.10,0.09,12.0
9,Jessie Nguyen,14.0,95.00,7,6.083333,1.250000,13.571429,No,56,2,...,0.04,0.11,0.08,0.02,0.07,0.20,0.67,0.07,0.07,12.0
10,Angel Knox,0.0,111.00,5,4.166667,1.250000,22.200000,No,47,1,...,0.00,0.07,0.21,0.00,0.04,0.41,0.95,0.06,0.05,12.0
11,Giancarlo Phillips,0.0,174.00,15,9.083333,1.583333,11.600000,No,79,1,...,0.04,0.13,0.18,0.01,0.04,0.29,0.82,0.06,0.04,12.1
12,Kristen Ellison,0.0,92.00,10,8.166667,1.250000,9.200000,No,63,2,...,0.04,0.00,0.11,0.02,0.06,0.11,0.70,0.03,0.08,12.0
13,Bailey Crane,0.0,42.00,3,4.166667,1.000000,14.000000,No,39,1,...,0.05,0.09,0.11,0.11,0.05,0.08,0.13,0.03,0.01,12.0
14,Jazlyn Bond,0.0,32.00,3,4.166667,1.916667,10.666667,No,38,1,...,0.03,0.10,0.11,0.06,0.08,0.12,0.51,0.06,0.06,12.0
15,Annabella Guerrero,0.0,331.00,16,6.500000,1.083333,20.687500,No,69,3,...,0.04,0.23,0.05,0.01,0.02,0.15,0.95,0.00,0.00,16.0
16,Maliyah Stephens,0.0,31.00,5,4.500000,1.166667,6.200000,No,41,1,...,0.04,0.20,0.14,0.00,0.08,0.27,0.91,0.11,0.10,13.6
17,Charlie English,0.0,146.00,12,10.250000,0.333333,12.166667,No,91,1,...,0.02,0.09,0.13,0.05,0.08,0.17,0.82,0.08,0.07,12.0
18,Gemma Solomon,0.0,70.07,12,8.500000,1.666667,5.839167,No,53,2,...,0.07,0.16,0.31,0.02,0.02,0.38,0.77,0.09,0.07,12.0
19,Wade Kaiser,0.0,47.00,6,3.166667,1.250000,7.833333,No,33,3,...,0.05,0.09,0.20,0.01,0.06,0.33,0.49,0.07,0.05,12.0
20,Lukas Madden,0.0,67.00,8,3.083333,1.000000,8.375000,No,35,3,...,0.00,0.10,0.16,0.03,0.05,0.27,0.61,0.07,0.05,12.2
21,Jovanni Sanchez,0.0,220.00,13,5.083333,1.333333,16.923077,No,58,2,...,0.09,0.13,0.18,0.01,0.08,0.04,0.20,0.05,0.06,14.0
22,Rishi Larson,0.0,31.00,6,4.333333,1.250000,5.166667,No,35,3,...,0.03,0.03,0.00,0.11,0.03,0.06,0.74,0.11,0.07,8.9
23,Valentino Orr,0.0,183.00,18,10.250000,1.166667,10.166667,No,76,1,...,0.04,0.10,0.29,0.00,0.01,0.14,0.87,0.06,0.05,13.1
24,Ireland Weiss,0.0,30.00,2,2.500000,1.250000,15.000000,No,23,1,...,0.05,0.13,0.17,0.01,0.09,0.33,0.66,0.08,0.05,12.5
25,Billy Doyle,0.0,43.00,6,4.416667,1.750000,7.166667,No,41,1,...,0.04,0.08,0.08,0.10,0.03,0.19,0.62,0.02,0.06,12.0
26,Bobby Moran,0.0,299.00,22,9.416667,1.250000,13.590909,No,92,1,...,0.04,0.15,0.20,0.01,0.04,0.18,0.76,0.07,0.07,12.0
27,Tania Velasquez,0.0,172.00,14,5.416667,1.250000,12.285714,No,59,1,...,0.02,0.10,0.12,0.11,0.09,0.26,0.81,0.06,0.08,12.0
28,Kathryn Watson,0.0,25.00,1,1.750000,1.750000,25.000000,No,17,1,...,0.09,0.06,0.11,0.02,0.03,0.57,0.83,0.06,0.03,14.0
29,Lillianna Wall,0.0,145.00,6,3.166667,1.333333,24.166667,No,40,2,...,0.01,0.08,0.10,0.16,0.22,0.18,0.78,0.08,0.06,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19970,Malik Jacobson,0.0,45.00,3,1.416667,1.000000,15.000000,No,19,3,...,0.01,0.05,0.25,0.04,0.06,0.25,0.84,0.06,0.06,12.0
19971,Elsie Mata,0.0,152.00,14,10.500000,1.083333,10.857143,No,74,1,...,0.03,0.10,0.13,0.05,0.08,0.33,0.81,0.05,0.06,12.0
19972,Teresa Colon,0.0,172.00,12,6.083333,1.000000,14.333333,No,57,4,...,0.12,0.24,0.17,0.03,0.12,0.04,0.72,0.07,0.10,12.0
19973,Kenya Ho,0.0,115.00,10,9.166667,1.750000,11.500000,No,58,2,...,0.03,0.14,0.12,0.06,0.10,0.23,0.63,0.05,0.06,12.5
19974,Chad Hurley,0.0,168.00,9,4.166667,1.083333,18.666667,No,48,3,...,0.03,0.15,0.14,0.01,0.04,0.14,0.65,0.06,0.06,12.0
19975,Rebekah Gould,0.0,25.00,2,2.416667,1.333333,12.500000,No,22,1,...,0.03,0.10,0.15,0.06,0.08,0.15,0.60,0.05,0.04,12.0
19976,Braydon Parrish,0.0,15.00,1,1.083333,1.083333,15.000000,No,13,1,...,0.01,0.26,0.12,0.00,0.08,0.17,0.77,0.06,0.12,15.2
19977,Kaleb Valencia,0.0,95.00,9,8.333333,1.083333,10.555556,No,57,1,...,0.05,0.09,0.23,0.03,0.06,0.21,0.68,0.04,0.10,13.0
19978,Ian Stone,0.0,66.00,5,2.416667,1.833333,13.200000,No,31,2,...,0.03,0.13,0.15,0.01,0.04,0.12,0.64,0.06,0.05,12.1
19979,Raina Hawkins,0.0,67.00,8,4.166667,1.333333,8.375000,No,42,3,...,0.05,0.13,0.08,0.00,0.08,0.07,0.74,0.04,0.06,12.0
19980,Regina Romero,0.0,25.00,2,3.083333,1.916667,12.500000,No,27,1,...,0.06,0.00,0.06,0.13,0.10,0.33,0.81,0.06,0.07,12.0
19981,Ryan Galloway,8.0,93.00,17,10.083333,1.083333,5.470588,No,59,3,...,0.02,0.08,0.13,0.15,0.19,0.21,0.74,0.05,0.09,12.0
19982,Samuel Grimes,0.0,161.00,19,10.333333,1.250000,8.473684,No,70,1,...,0.09,0.10,0.19,0.03,0.14,0.23,0.87,0.06,0.06,13.0
19983,Dexter Mcneil,0.0,94.00,9,4.083333,1.916667,10.444444,No,24,1,...,0.03,0.12,0.19,0.00,0.00,0.14,0.89,0.11,0.02,12.0
19984,Alvaro Garrison,0.0,48.00,11,6.000000,0.083333,4.363636,No,67,4,...,0.01,0.08,0.11,0.13,0.19,0.37,0.91,0.07,0.11,12.0
19985,Antoine Fischer,0.0,117.00,8,8.333333,1.250000,14.625000,No,68,1,...,0.02,0.12,0.16,0.02,0.05,0.23,0.86,0.06,0.05,12.0
19986,Dane Griffith,0.0,15.00,1,1.416667,1.416667,15.000000,No,15,1,...,0.01,0.10,0.10,0.09,0.10,0.25,0.69,0.06,0.05,12.0
19987,Julianne Rowe,0.0,109.00,6,3.416667,1.250000,18.166667,No,42,2,...,0.00,0.24,0.18,0.01,0.13,0.14,0.53,0.05,0.06,14.0
19988,Kenzie Schmidt,0.0,46.00,3,3.166667,1.166667,15.333333,No,32,2,...,0.04,0.18,0.13,0.01,0.04,0.10,0.41,0.03,0.02,14.0
19989,Marlee Christian,8.0,114.00,18,8.500000,1.166667,6.333333,No,60,3,...,0.04,0.06,0.20,0.09,0.22,0.17,0.71,0.07,0.07,12.0
19990,Heaven Fischer,0.0,25.00,2,1.500000,1.083333,12.500000,No,18,2,...,0.02,0.09,0.10,0.00,0.07,0.20,0.73,0.07,0.06,12.0
19991,Garrett Burns,0.0,30.00,2,2.166667,1.416667,15.000000,No,19,1,...,0.01,0.08,0.14,0.00,0.02,0.10,0.65,0.06,0.08,12.0
19992,Eli Spencer,0.0,471.00,22,10.583333,1.500000,21.409091,No,83,1,...,0.04,0.20,0.20,0.00,0.02,0.05,0.46,0.08,0.09,12.4
19993,Elisabeth Stout,0.0,33.00,3,6.083333,1.166667,11.000000,No,31,1,...,0.03,0.12,0.20,0.00,0.09,0.13,0.49,0.05,0.08,12.0
19994,Darwin Mcknight,0.0,94.00,10,1.083333,0.250000,9.400000,No,42,1,...,0.07,0.09,0.15,0.01,0.09,0.29,0.85,0.06,0.05,13.2
19995,Victoria Lutz,0.0,47.00,8,3.416667,1.000000,5.875000,No,24,4,...,0.03,0.17,0.21,0.00,0.06,0.12,0.16,0.02,0.03,14.0
19996,Lilyana Ramirez,0.0,125.00,7,5.166667,1.166667,17.857143,No,49,3,...,0.01,0.05,0.09,0.00,0.03,0.16,0.89,0.05,0.24,14.0
19997,Camille Howell,0.0,109.50,16,10.583333,1.250000,6.843750,No,68,4,...,0.03,0.01,0.20,0.04,0.15,0.26,0.88,0.06,0.05,12.0
19998,Natalie Tapia,0.0,112.00,11,10.166667,1.583333,10.181818,No,66,2,...,0.04,0.12,0.14,0.02,0.06,0.13,0.77,0.05,0.05,12.0
19999,Jaylene Vargas,0.0,243.00,15,10.083333,1.166667,16.200000,No,67,2,...,0.03,0.13,0.24,0.02,0.07,0.24,0.41,0.02,0.04,14.0

In [14]:
#Getting the number of rows and columns
csv_file.shape  #20,000 rows, 27 columns

(20000, 27)

In [15]:
#Listing the first ten rows of data and the variable names
csv_file.head(10)

,Name,Donation,Lifetime,Gifts,YearsSinceFirst,YearsSinceLast,AvgGift,MajorDonor,Promotions,RecentGifts,...,Technical,Sales,Clerical,Farmers,SelfEmployed,Cars,OwnerOccupied,Age55_59,Age60_64,School
0,Yandel Leach,0.0,81.0,15,6.416667,1.166667,5.400000,No,58,3,...,0.07,0.17,0.22,0.01,0.02,0.16,0.41,0.04,0.05,14.0
1,Jaylah Sims,15.0,15.0,1,1.166667,1.166667,15.000000,No,13,1,...,0.01,0.14,0.16,0.01,0.06,0.08,0.90,0.07,0.11,12.0
2,Roger Bush,0.0,15.0,1,1.750000,1.750000,15.000000,No,16,1,...,0.00,0.05,0.32,0.00,0.00,0.03,0.12,0.06,0.03,12.0
3,Maddox Horn,0.0,25.0,2,3.500000,1.250000,12.500000,No,26,1,...,0.07,0.16,0.19,0.06,0.21,0.52,0.79,0.03,0.02,12.3
4,Darrell Walters,0.0,20.0,1,1.333333,1.333333,20.000000,No,12,1,...,0.03,0.07,0.15,0.02,0.05,0.22,0.78,0.06,0.06,12.0
5,Nick Kent,0.0,68.0,6,7.000000,1.583333,11.333333,No,38,2,...,0.02,0.07,0.04,0.14,0.17,0.26,0.67,0.06,0.05,12.0
6,Isabel Curry,0.0,110.0,11,10.166667,1.416667,10.000000,No,38,2,...,0.03,0.05,0.12,0.15,0.15,0.21,0.82,0.08,0.05,12.0
7,Levi Leon,0.0,174.0,26,10.416667,1.500000,6.692308,No,72,3,...,0.04,0.09,0.12,0.01,0.04,0.12,0.57,0.06,0.06,12.0
8,Zack Bradshaw,0.0,20.0,1,1.750000,1.750000,20.000000,No,15,1,...,0.02,0.16,0.18,0.03,0.03,0.22,0.90,0.10,0.09,12.0
9,Jessie Nguyen,14.0,95.0,7,6.083333,1.250000,13.571429,No,56,2,...,0.04,0.11,0.08,0.02,0.07,0.20,0.67,0.07,0.07,12.0

In [16]:
#Using python to identify numeric and character variables
csv_file.dtypes
#numeric variables are represented as floats or integers 
#while character variables are represented as objects

Name                object
Donation           float64
Lifetime           float64
Gifts                int64
YearsSinceFirst    float64
YearsSinceLast     float64
AvgGift            float64
MajorDonor          object
Promotions           int64
RecentGifts          int64
Age                float64
HomePhone           object
PCOwner             object
CatalogShopper       int64
PerCapIncome         int64
MedHouseInc          int64
Professional       float64
Technical          float64
Sales              float64
Clerical           float64
Farmers            float64
SelfEmployed       float64
Cars               float64
OwnerOccupied      float64
Age55_59           float64
Age60_64           float64
School             float64
dtype: object